mkdir -p dist/day1/
cp src/day1/input.txt dist/day1/
cp src/day2/input.txt dist/day2/
cp src/day3/input.txt dist/day3/
cp src/day4/input.txt dist/day4/
cp src/day5/input.txt dist/day5/
cp src/day6/input.txt dist/day6/
cp src/day7/input.txt dist/day7/
cp src/day8/input.txt dist/day8/
